server:
  port: 7777
  
spring:
  application:
    name: emailservice
  batch:
    job:
      enabled:false 
eureka:
  client:
    enabled: true
    # healthcheck:
      # enabled: true
    serviceUrl:
      defaultZone: http://microservices-eureka-service:8761/eureka/
  instance:
     hostname: emailservice
   

